# Generated by Django 4.1.2 on 2022-10-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=250)),
                ('flag', models.CharField(max_length=250)),
                ('info', models.TextField(max_length=500)),
                ('population', models.IntegerField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
