# Generated by Django 4.1.2 on 2022-10-06 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_continent'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='continent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='countrys', to='main_app.continent'),
        ),
    ]
