# Generated by Django 4.1.2 on 2022-10-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_language_family_language_script_language_speakers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='family',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='language',
            name='script',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='language',
            name='speakers',
            field=models.IntegerField(),
        ),
    ]
