# Generated by Django 4.1.2 on 2022-10-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_language_family_alter_language_script_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='languages',
            field=models.ManyToManyField(to='main_app.language'),
        ),
    ]
